file_path: "datasets/titanic.xlsx"
target_column: "Survived"
drop_columns: ["PassengerId", "Name"]
splits:
  test_size: 0.2
  val_size: 0.2
random_state: 42
imbalance:
  apply_smote: false
  threshold: 0.3
preprocessing:
  save_dir: "experiments/preprocessing/artifacts"
  apply_scaling: true # Set to false for tree models
output:
  save_processed_data: true
  debug_splits: true
  debug_splits_dir: "experiments/preprocessing/debug_splits"
